baseURL = '//blog.mkdef.com/leetcode-notebook-rs/'
languageCode = 'zh-hans'
title = 'LeetCode NoteBook in Rust'
theme = "hugo-book"

# https://github.com/gohugoio/hugo/issues/7182
relativeURLs = true
canonifyURLs = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = true

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  BookSection = '*'